# Generated by Django 4.1.5 on 2023-01-22 15:51

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("skillblog", "0002_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="resume",
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
